ZSH_DISABLE_COMPFIX=true

# Setup the PATH
export PATH="bin:vendor/bin:node_modules/.bin:/home/djeg/.gem/ruby/2.5.0/bin:$HOME/.bin:$HOME/.node_modules/bin:$HOME/.symfony5/bin:$HOME/.local/bin:$PATH:$HOME/.rvm/bin:$HOME/.composer/vendor//root/.gem/ruby/2.5.0/bin/root/.gem/ruby/2.5.0/binbin:$HOME/.config/composer/vendor/bin:$GOPATH/bin:$HOME/.gem/ruby/2.6.0/bin:/opt/android-sdk:/opt/android-sdk/tools:/opt/android-sdk/plateforms" # Add RVM to PATH for scripting

export ZSH_CONFIG="$HOME/.config/zsh"

# Mise trusted config path
MISE_TRUSTED_CONFIG_PATHS="$HOME/Projects"

# ZINIT
ZINIT_HOME="$HOME/.config/zinit"

if [ ! -d "$ZINIT_HOME" ]; then
  mkdir -p "$(dirname "$ZINIT_HOME")"

  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

source "$ZINIT_HOME/zinit.zsh"

# theme
zinit ice depth=1; zinit light sindresorhus/pure

# vi mode
set -o vi
zinit ice depth=1
zinit light jeffreytse/zsh-vi-mode

# Zsh Syntax And Completion
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-completions
zinit light Aloxaf/fzf-tab

# Load completion
autoload -U compinit && compinit
zinit cdreplay -q

# History
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase

setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# Shell integrations
eval "$(fzf --zsh)"
eval "$(zoxide init --cmd cd zsh)"
eval "$(mise activate zsh)"

# loading custom file
source $ZSH_CONFIG/exports.sh
source $ZSH_CONFIG/aliases.sh
source $HOME/.localrc

# bun completions
[ -s "/Users/djeg/.bun/_bun" ] && source "/Users/djeg/.bun/_bun"
